export const DUMMY_STUDY_DATA = {
  info: '이것은 소개입니다요',
  members: [
    {
      userId: 123,
      nickname: '강동옥',
      isRoomMaker: true,
      profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
    },
    {
      userId: 124,
      nickname: '박준영',
      isRoomMaker: false,
      profileImg:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4SriYhmFVv_AhZ1z_Ountaxo_ZvZboLQWrqR2_hgIeSF60wuLKN4PXkGRIb-XuYrLZeI&usqp=CAU',
    },
    {
      userId: 1224,
      nickname: '성아영',
      isRoomMaker: false,
      profileImg:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD30NUzX2ebvuKlzc-zSgWQFo46-3w-kavIIJx-4kf65IZf81QtwM-foFjhXpq-Apb7zI&usqp=CAU',
    },
  ],
  scheduleListRes: [
    {
      finishedAt: '2022-04-05T01:27:40.544Z',
      id: 12,
      startedAt: '2022-04-05T01:27:40.544Z',
    },
    {
      finishedAt: '2022-04-18T01:27:40.544Z',
      id: 15,
      startedAt: '2022-04-18T01:27:40.544Z',
    },
    {
      finishedAt: '2022-04-25T01:27:40.544Z',
      id: 122,
      startedAt: '2022-04-25T01:27:40.544Z',
    },
  ],
  title: '알고리즘 스터디',
};

// [
//   {
//     id: 1234,
//     startedAt: '2022-04-22T12:32:07.332Z',
//     studyId: 111,
//     toSolveProblems: [
//       {
//         id: 1285,
//         inputs: ['string'],
//         level: 0,
//         number: 0,
//         outputs: ['string'],
//         title: '임시문제제목',
//       },
//     ],
//   },
//   {
//     id: 1334,
//     startedAt: '2022-04-25T12:32:07.332Z',
//     studyId: 1211,
//     toSolveProblems: [
//       {
//         id: 1285,
//         inputs: ['string'],
//         level: 0,
//         number: 0,
//         outputs: ['string'],
//         title: '임시문제제목2',
//       },
//     ],
//   },
// ];

export const DUMMY_SCHEDULE_RES_DATA = {
  finishedAt: '2022-04-27T02:44:44.587Z',
  problemListRes: [
    {
      level: 8,
      problemNumber: 1003,
      solvedMemberList: [
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'jer0618',
          id: 1,
          info: '인포인포',
          nickname: '강동옥',
          preferredLanguage: 'python3',
          profileImg: 'https://t1.daumcdn.net/cfile/tistory/216C553953FC27C335',
          theme: 'basic',
          username: 'jer0618',
        },
        {
          bojId: 'kelvin9149',
          id: 2,
          info: '인포인포인포인포',
          nickname: '양지훈',
          preferredLanguage: 'java',
          profileImg:
            'https://s3.ap-northeast-2.amazonaws.com/elasticbeanstalk-ap-northeast-2-176213403491/media/magazine_img/magazine_302/104_%E1%84%8A%E1%85%A5%E1%86%B7%E1%84%82%E1%85%A6%E1%84%8B%E1%85%B5%E1%86%AF.jpg',
          theme: 'dark',
          username: 'kelvin9149',
        },
      ],
      startedAt: '2022-04-27T02:44:44.587Z',
      title: '피보나치 함수',
    },
    {
      level: 17,
      problemNumber: 1006,
      solvedMemberList: [
        {
          bojId: 'ayoung0924',
          id: 3,
          info: '인포인포인포인포인포인포',
          nickname: '성아영',
          preferredLanguage: 'python3',
          profileImg:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4SriYhmFVv_AhZ1z_Ountaxo_ZvZboLQWrqR2_hgIeSF60wuLKN4PXkGRIb-XuYrLZeI&usqp=CAU',
          theme: 'peachpink',
          username: 'ayoung0924',
        },
        {
          bojId: 'roywnsdud',
          id: 4,
          info: '인포인포인포인포인포인포인포인포',
          nickname: '박준영',
          preferredLanguage: 'cpp',
          profileImg:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD30NUzX2ebvuKlzc-zSgWQFo46-3w-kavIIJx-4kf65IZf81QtwM-foFjhXpq-Apb7zI&usqp=CAU',
          theme: 'olivegreen',
          username: 'roywnsdud',
        },
      ],
      startedAt: '2022-04-27T02:44:44.587Z',
      title: '컨닝',
    },
  ],
  startedAt: '2022-04-27T02:44:44.587Z',
};
